sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: GhxhDN4+pM58R8Nhyj7OCIGxY9qsqjA4zu7Gq3P7r0c9xdBfYo8MCvMpTODNgjbff1ooqJarDWWwlOuVoSTW6Nn4ZJme80k5GRw09L3Iw6HS6mj2io8o3ihHsNulN9keXbUqRjm448yMSjiTqU/5qd8XSfEe7rtM+dIcsOgJqWwpR9iwtMCmlQgzqo51GDNQUhqVbqdZmeCWXt7xgfcn+fgxxqFP1OGyKQjwlqO5gxB6VTzuA0Euv4VoVrxURvjv6/dscAPfuKHuIWj7LV/RYrJrNxpwYgnCiyf+s3kHAwlAbIxA4hIXlJnIV8TaE/sRwnBXmuOWEh/17ldhXbWq6V4diR/Xh+i/Pt5Q1MUZwmNdLVivd6dWqSr4SEIm/Cn5Wrq9v0m7x08kX77nnNHpo2jxacfCX1aHFS83DCoXeiWFFpQqbao4Twhk0jJKtplgUE3Q3RfXQ5jGTQmBlf9F4YZKfyhqPbcD7eOIZ01qGZ/aPpoNok3jMZ0TaAEmwule1MK/UMWpbc4zhxjqblCWDlsMpcrhC4b15nekcA5hqDDtpkJt6PP4//md9VFXi+biSiJDf8yudWcbyVY1htHvPi+mlEwMnY2R2Ta/QpxJGI5h1dNGsDmyO+I0NSHiPK93bq2pkaQPybleZgMWD4XSG7WhjxUFe+FvmMNuJQJk6es=
  - secure: ROzLnvCqgXDNgSq6EYd+N526s+a5Q/YZKGgIRGgf/gZOvEXyYuCgFP5KotTBMF7D/Wa6EJDZw6X3Ky5ePLitsPmLVuxhEGvEdRQmzoKRv4PumYlxPpJnUn0CXauQzGF/wWgGK5pMgRki6xAl29zxazsWMB6Sy+HQOkorXqWDtZXWWvYLn4ZxAYUWFhIl5nwHKU1qJmWfNxWrgp1mMue9VkulCXrJGscNllOr3hOv3Oq6ukvIs82ocr+lOMKjLerz9NO7k4wQfyog8QZsL77Xs3GSlvS4D4OpqZySMhj/EudmttzjnfNGzmPpUOAbMK5tW0W+ItOkQ/oKXArtGAKU6MRC57ID5wM8UscjEr97hKJEB39obx1gmbRt9ZaSEK69/Ky0uOeibOt17yZ1olpz67P8PqQd/kKYQ8INUH4Z/3WoI0nM9x9UHFdzk4z4QzIDuZKjDYPClSMszKFg8QyPuLLh5XKo39Htali94Ss2wvlsh9vdPp4UqnD9yjlFH+tCo/RCb0muIJmmGGmX3oDZcZxjYINfhXk1JbceF+pcO9areAAwk9xTEE5NhoaQwOcomPqS/Yh6aI2In+RYJ0Fi13W1Jh5s63a0GdKQu78+DL5iq8iPI8YTsKCgpEca+fXE+m4M0fiS/TWwZttlbHXG6ejc7mcTfK+O/Gntu0v8geM=
